language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  env:
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.2
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
script: python manage.py runserver
branches:
  only:
    - master
